server:
  port: 8084

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://localhost:5236/DMSERVER
    username: PSP_COCKPIT
    password: PSP_COCKPIT

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  # ???????package?????????
  typeAliasesPackage: com.gstool.common.model.entity
  global-config:
    # ???????
    db-config:
      # ID??
      id-type: ASSIGN_ID
      # ??????
      logic-delete-value: 1
      # ??????
      logic-not-delete-value: 0
  # ????
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE